# Generated by Django 5.1.3 on 2024-11-14 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_puesto', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_puesto', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoArea',
            fields=[
                ('id_empleado_area', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='EMPLEADOS.area')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='EMPLEADOS.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='EMPLEADOS.puesto'),
        ),
    ]
